🩹 Add missing dependecy lxml[html_clean]
Fixes the error

ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
  Install lxml[html_clean] or lxml_html_clean directly.